### ISSUE TITLE
Broken Link in Docs and Articles Section

### ISSUE THREAD

**Issue by count-of-monte-keystone** [lgg/awesome-keepass#17]
In the Docs and Articles section, the Reverse Engineered KeePass (KDBX) File Format link is broken.

**Comment by lgg** [comment]
Need help with recovering this data from web archives

**Comment by juev** [comment]
Email was not delivered. So sad. Maybe @luelista can reply hear?

**Comment by lgg** [comment]
Tried wayback machine: 
- https://web.archive.org/web/*/https://github.com/max-weller/kdbx-viewer/*
- https://web.archive.org/web/20170910080727/https://max-weller.github.io/kdbx-viewer/
- https://web.archive.org/web/20191122153804/http://home.max-weller.de/journal/

>[Format specification](https://web.archive.org/web/20170910080727/https://max-weller.github.io/kdbx-viewer/kdbx_format.html) of .kdbx files (by jhagmar)

@juev check it. it seems that this is what we were looking for
- https://github.com/luelista/kdbxviewer/blob/master/doc/kdbx_format.html
- https://github.com/jhagmar/cryptkeyper/blob/master/doc/kdbx_format.txt
- https://web.archive.org/web/20160528151935/http://blog.sharedmemory.fr/en/2014/04/30/keepass-file-format-explained/

also this seems to be useful:
- https://gist.github.com/msmuenchen/9318327
- https://github.com/keepassxreboot/keepassxc-specs/blob/master/kdbx-xml/rfc.md
- https://keepass.info/help/kb/kdbx_4.html
- https://gist.github.com/lgg/e6ccc6e212d18dd2ecd8a8c116fb1e45
- https://gist.github.com/berlam/2fc3146e7c8420cbbf99

**Comment by lgg** [comment]
@juev what do you think about creating pull request with folder `doc` and cleared `.html`/`.txt` spec files

**Comment by juev** [comment]
@lgg done, but I just add spec files without changing readme.

If you have some remarks, please let me know.

**Comment by pepa65** [comment]
I have modified the @luelista sources (a bit more user friendly for my usage), and I have been using the result for many years now: https://github.com/pepa65/kdbxviewer

**Comment by luelista** [comment]
Hi, I put it up on a new domain, you can change the link to this if you want: http://luelista.net/kdbxviewer/kdbx_format/

**Comment by pepa65** [comment]
Great documentation on those pages!
So is it Max->Mira..?
