### ISSUE TITLE
Linux Clients?

### ISSUE THREAD

**Issue by akhiljalagam** [lgg/awesome-keepass#20]
Does Linux not have an official KeePass client?

**Comment by lgg** [comment]
Following the official website - they recommend to use Wine/Mono for running app on Linux.

https://keepass.info/download.html

![image](https://user-images.githubusercontent.com/12018713/206864662-ef5141ce-e417-4e12-b957-a7cbd3bdb41e.png)

**Comment by lgg** [comment]
> There are some native Linux clients for KeePass. https://keepassxc.org/ is one of them.

Yes, but you were asking about "official" version:

![image](https://user-images.githubusercontent.com/12018713/209186794-3276e406-d139-4d1b-bcc6-e8ff3f1d61aa.png)
![image](https://user-images.githubusercontent.com/12018713/209186855-ec84a88a-6643-4820-a4f0-82d773004b9d.png)

Also you can use KeeWeb as Desktop app on Linux as I do, but this is still an unofficial version, compared to KeePass under Windows from official website: https://keepass.info/

**Comment by akhiljalagam** [comment]
It would be great if the list shows unofficial clients too. keepassxc is awesome BTW.

**Comment by lgg** [comment]
This repo already contain KeepassXC (https://github.com/lgg/awesome-keepass/blob/master/README.md?plain=1#L36) and also KeepassXC-related items: (https://github.com/lgg/awesome-keepass/blob/master/README.md?plain=1#L127)
